license_id: hdx-other
license_other: https://www.imf.org/en/about/copyright-and-terms
methodology: Other
methodology_other:  |
  [Tracking Trade from Space: An Application to Pacific Island Countries](https://www.imf.org/en/publications/wp/issues/2021/08/20/tracking-trade-from-space-an-application-to-pacific-island-countries-464345)

  [Nowcasting Global Trade from Space](https://www.imf.org/en/publications/wp/issues/2025/05/16/nowcasting-global-trade-from-space-566957)
caveats:
dataset_source: UN Global Platform; IMF PortWatch
package_creator: HDX Data Systems Team
private: False
maintainer: 1d7ceaf2-06c0-49f8-a871-fc974a07ed75
owner_org: 22945e84-d492-497f-9ffa-f9c6c394c04f
notes: Daily count of port calls, estimates of incoming shipment volumes and outgoing shipment volumes (in metric tons) for ports in [country].
